project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - resume.qmd
    - blog.qmd
    - "posts/*/*.qmd"
    - "!templates/**"

website:
  title: "My Portfolio"
  description: "Intro to Data Science Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/yourusername

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-fold: false
